## overview

In [1]:
# default package
import logging
import sys 
import os
import pathlib
import IPython
import random
from urllib.request import urlretrieve

In [2]:
# third party package
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn
from tqdm import tqdm
import seaborn as sns
# torch
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [3]:
# my package
sys.path.append(os.path.join(pathlib.Path().resolve(),"../"))

In [4]:
# reload settings
%load_ext autoreload
%autoreload 2

In [5]:
# logger
logger=logging.getLogger(__name__)
logging.basicConfig(level=logging.ERROR)

In [6]:
# graph setting
sns.set()

In [7]:
# gpu
torch.cuda.is_available()

True

In [8]:
# global parameter
DATA_DIR="../dlwpt-code/data/"

## tensor

In [9]:
img_t=torch.randn(3,5,5)
batch_t=torch.randn(2,3,5,5)

In [10]:
img_t.mean(-3).shape,batch_t.mean(-3).shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

### 名前付き

In [11]:
weights=torch.tensor([0.2126, 0.7152, 0.0722],names=["channels"])
img_named=img_t.refine_names(...,"channels","rows","columns")

<ipython-input-11-bc1c4fbfcd56>:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:848.)
  weights=torch.tensor([0.2126, 0.7152, 0.0722],names=["channels"])


In [12]:
weights.align_as(img_named).names

('channels', 'rows', 'columns')

### dtype

In [13]:
img_t.dtype

torch.float32

In [14]:
img_t.double().dtype

torch.float64

### API

In [15]:
a=torch.randn(3,2)
a_t=torch.transpose(a,0,1)
a_t.shape

torch.Size([2, 3])

### storage

In [16]:
a,a.storage()

(tensor([[-1.5056, -0.9232],
         [ 0.3690, -2.0561],
         [-0.0121,  0.5038]]),
  -1.505574107170105
  -0.923231303691864
  0.36900636553764343
  -2.0561304092407227
  -0.012131568044424057
  0.5037778615951538
 [torch.FloatStorage of size 6])

In [17]:
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

### meta

In [18]:
a=torch.tensor([[2,1],[3,2],[4,5]])
a[1].storage_offset()

2

In [19]:
a.stride()

(2, 1)

In [20]:
sub=a[1].clone()

In [21]:
a.t()

tensor([[2, 3, 4],
        [1, 2, 5]])

### GPU

In [22]:
a=torch.tensor([[2,1],[3,2]],device="cuda")

In [23]:
a,a.cpu()

(tensor([[2, 1],
         [3, 2]], device='cuda:0'),
 tensor([[2, 1],
         [3, 2]]))

### NumPy

In [24]:
a=torch.tensor([[2,1],[3,2]])
a.numpy()

array([[2, 1],
       [3, 2]])

In [25]:
torch.from_numpy(np.array([1,2]))

tensor([1, 2])

## 演習問題

### 1

In [26]:
a=torch.tensor(list(range(9)))

In [27]:
a.size(),a.storage_offset(),a.stride()

(torch.Size([9]), 0, (1,))

In [28]:
b=a.view(3,3)
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [29]:
# 同じストレージを共有
id(b.storage())==id(a.storage())

True

In [30]:
c=b[1:,1:]

In [31]:
c.size(),c.storage_offset(),c.stride()

(torch.Size([2, 2]), 4, (3, 1))

### 2

In [32]:
torch.cos(a)

RuntimeError: cos_vml_cpu not implemented for 'Long'

In [33]:
b=a.float()
torch.cos(b)

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])